/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Telas.TelasCaronas.TelaChatWhats;
import Telas.TelasCaronas.TelaMinhasCaronas;
import Telas.TelasCaronas.TelaParticiparCarona;
import Telas.TelasCaronas.TelaRegrasDoCarro;
import Telas.TelasUsuarios.TelaExclusão;
import Telas.TelasCarro.TelaCadastroCar;
import Telas.TelasCarro.TelaCadastroMotorista;
import Telas.TelasCarro.TelaDadosMotoristaVazio;
import Telas.TelasCarro.TelaExcluirMotorista;
import Telas.TelasCarro.TelaExclusaoCarro;
import Telas.TelasConfigurações.TelaAlterarSenha;
import Telas.TelasUsuarios.TelaSemDados;
import Telas.TelasUsuarios.TelaAlteração;
import Telas.TelasUsuarios.TelaCadastroUser;
import Telas.TelasConfigurações.TelaSuporte;
import Telas.TelasConfigurações.TelaTermos;
import javax.swing.JOptionPane;

/**
 *
 * @author tutu momolada
 */
public class TelaMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaMenu.class.getName());

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(500, 350));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LogoDoMenu.jpg"))); // NOI18N

        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenu1.setBackground(java.awt.SystemColor.activeCaption);
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 1/user.png"))); // NOI18N
        jMenu1.setText("Usuários");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setBackground(java.awt.SystemColor.activeCaption);
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 1/user_add.png"))); // NOI18N
        jMenuItem1.setText("Cadastro");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem4.setBackground(java.awt.SystemColor.activeCaption);
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 1/folder_table.png"))); // NOI18N
        jMenuItem4.setText("Dados pessoais");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setBackground(java.awt.SystemColor.activeCaption);
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 1/page_white_wrench.png"))); // NOI18N
        jMenuItem5.setText("Alterar dados");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setBackground(java.awt.SystemColor.activeCaption);
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 1/cross.png"))); // NOI18N
        jMenuItem6.setText("Exluir conta");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(java.awt.SystemColor.activeCaption);
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 1/car.png"))); // NOI18N
        jMenu2.setText("Carros");

        jMenuItem7.setBackground(java.awt.SystemColor.activeCaption);
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 1/car_add.png"))); // NOI18N
        jMenuItem7.setText("Cadastro carro");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem2.setBackground(java.awt.SystemColor.activeCaption);
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 1/car_delete.png"))); // NOI18N
        jMenuItem2.setText("Ecluir carro");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem8.setBackground(java.awt.SystemColor.activeCaption);
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 1/user_add.png"))); // NOI18N
        jMenuItem8.setText("Cadastro Motorista");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem11.setBackground(java.awt.SystemColor.activeCaption);
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 1/user_delete.png"))); // NOI18N
        jMenuItem11.setText("Excluir Motorista");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem9.setBackground(java.awt.SystemColor.activeCaption);
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 1/folder_table.png"))); // NOI18N
        jMenuItem9.setText("Dados do Motorista");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(java.awt.SystemColor.activeCaption);
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 1/group.png"))); // NOI18N
        jMenu3.setText("Caronas");

        jMenu7.setBackground(java.awt.SystemColor.activeCaption);
        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 1/door_in.png"))); // NOI18N
        jMenu7.setText("Minhas caronas");

        jMenuItem3.setBackground(java.awt.SystemColor.activeCaption);
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 1/add.png"))); // NOI18N
        jMenuItem3.setText("Participar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem3);

        jMenuItem13.setBackground(java.awt.SystemColor.activeCaption);
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 1/cancel.png"))); // NOI18N
        jMenuItem13.setText("Sair");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem13);

        jMenu3.add(jMenu7);

        jMenuItem14.setBackground(java.awt.SystemColor.activeCaption);
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 1/door_out.png"))); // NOI18N
        jMenuItem14.setText("Oferecer carona");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem14);

        jMenuItem10.setBackground(java.awt.SystemColor.activeCaption);
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 1/table_error.png"))); // NOI18N
        jMenuItem10.setText("Regras do carro");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 1/comment.png"))); // NOI18N
        jMenuItem12.setText("Chat com Motorista");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuBar1.add(jMenu3);
        jMenuBar1.add(jMenu4);

        jMenu5.setBackground(java.awt.SystemColor.activeCaption);
        jMenu5.setForeground(new java.awt.Color(0, 0, 0));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 1/cog.png"))); // NOI18N
        jMenu5.setText("Configurações");

        jMenuItem15.setBackground(java.awt.SystemColor.activeCaption);
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 1/bell.png"))); // NOI18N
        jMenuItem15.setText("Suporte");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem15);

        jMenuItem16.setBackground(java.awt.SystemColor.activeCaption);
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 1/wrench.png"))); // NOI18N
        jMenuItem16.setText("Alterar senha");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem16);

        jMenuItem17.setBackground(java.awt.SystemColor.activeCaption);
        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 1/layout.png"))); // NOI18N
        jMenuItem17.setText("Termos de uso");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem17);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

    TelaCadastroUser TelaCadUser = new TelaCadastroUser();
        jDesktopPane1.add(TelaCadUser);
        int x = (jDesktopPane1.getWidth() - TelaCadUser.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - TelaCadUser.getHeight()) / 2;
        TelaCadUser.setLocation(x, y);
        TelaCadUser.setVisible(true);
 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        
        TelaSemDados TelaSD = new TelaSemDados();
        jDesktopPane1.add(TelaSD);
        int x = (jDesktopPane1.getWidth() - TelaSD.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - TelaSD.getHeight()) / 2;
        TelaSD.setLocation(x, y);
        TelaSD.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        TelaExclusaoCarro TelaExcCar = new TelaExclusaoCarro();
        jDesktopPane1.add(TelaExcCar);
        int x = (jDesktopPane1.getWidth() - TelaExcCar.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - TelaExcCar.getHeight()) / 2;
        TelaExcCar.setLocation(x, y);
        TelaExcCar.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        
        TelaCadastroCar TelaCadCar = new TelaCadastroCar();
        jDesktopPane1.add(TelaCadCar);
        int x = (jDesktopPane1.getWidth() - TelaCadCar.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - TelaCadCar.getHeight()) / 2;
        TelaCadCar.setLocation(x, y);
        TelaCadCar.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        
        TelaSuporte TelaSup = new TelaSuporte();
        jDesktopPane1.add(TelaSup);
        int x = (jDesktopPane1.getWidth() - TelaSup.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - TelaSup.getHeight()) / 2;
        TelaSup.setLocation(x, y);
        TelaSup.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        
        TelaAlteração TelaAlt = new TelaAlteração();
        jDesktopPane1.add(TelaAlt);
        int x = (jDesktopPane1.getWidth() - TelaAlt.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - TelaAlt.getHeight()) / 2;
        TelaAlt.setLocation(x, y);
        TelaAlt.setVisible(true);
       
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        
        TelaExclusão TelaExc = new TelaExclusão();
        jDesktopPane1.add(TelaExc);
        int x = (jDesktopPane1.getWidth() - TelaExc.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - TelaExc.getHeight()) / 2;
        TelaExc.setLocation(x, y);
        TelaExc.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        
        TelaRegrasDoCarro TelaReg = new TelaRegrasDoCarro();
        jDesktopPane1.add(TelaReg);
        int x = (jDesktopPane1.getWidth() - TelaReg.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - TelaReg.getHeight()) / 2;
        TelaReg.setLocation(x, y);
        TelaReg.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        
        TelaExcluirMotorista TelaExcMot = new TelaExcluirMotorista();
        jDesktopPane1.add(TelaExcMot);
        int x = (jDesktopPane1.getWidth() - TelaExcMot.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - TelaExcMot.getHeight()) / 2;
        TelaExcMot.setLocation(x, y);
        TelaExcMot.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        
        TelaAlterarSenha TelaAltSenha = new TelaAlterarSenha();
        jDesktopPane1.add(TelaAltSenha);
        int x = (jDesktopPane1.getWidth() - TelaAltSenha.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - TelaAltSenha.getHeight()) / 2;
        TelaAltSenha.setLocation(x, y);
        TelaAltSenha.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed

        TelaTermos TelaTermosDeUso = new TelaTermos();
        jDesktopPane1.add(TelaTermosDeUso);
        int x = (jDesktopPane1.getWidth() - TelaTermosDeUso.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - TelaTermosDeUso.getHeight()) / 2;
        TelaTermosDeUso.setLocation(x, y);
        TelaTermosDeUso.setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        
        TelaCadastroMotorista TelaCadMot = new TelaCadastroMotorista();
        jDesktopPane1.add(TelaCadMot);
        int x = (jDesktopPane1.getWidth() - TelaCadMot.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - TelaCadMot.getHeight()) / 2;
        TelaCadMot.setLocation(x, y);
        TelaCadMot.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        
        TelaDadosMotoristaVazio TelaDadosMotVazio = new TelaDadosMotoristaVazio();
        jDesktopPane1.add(TelaDadosMotVazio);
        int x = (jDesktopPane1.getWidth() - TelaDadosMotVazio.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - TelaDadosMotVazio.getHeight()) / 2;
        TelaDadosMotVazio.setLocation(x, y);
        TelaDadosMotVazio.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        
        TelaChatWhats TelaChat = new TelaChatWhats();
        jDesktopPane1.add(TelaChat);
        int x = (jDesktopPane1.getWidth() - TelaChat.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - TelaChat.getHeight()) / 2;
        TelaChat.setLocation(x, y);
        TelaChat.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        
        TelaParticiparCarona TelaPartC = new TelaParticiparCarona();
        jDesktopPane1.add(TelaPartC);
        int x = (jDesktopPane1.getWidth() - TelaPartC.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - TelaPartC.getHeight()) / 2;
        TelaPartC.setLocation(x, y);
        TelaPartC.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        
        JOptionPane.showMessageDialog(this, "Você saiu !");
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        
        TelaMinhasCaronas TelaMinhasCarona = new TelaMinhasCaronas();
        jDesktopPane1.add(TelaMinhasCarona);
        int x = (jDesktopPane1.getWidth() - TelaMinhasCarona.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - TelaMinhasCarona.getHeight()) / 2;
        TelaMinhasCarona.setLocation(x, y);
        TelaMinhasCarona.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
